/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить список всех типов событий.
         *     Доступно как владельцу, так и гостям (для выбора при бронировании).
         */
        get: operations["EventTypesApi_listEventTypes"];
        put?: never;
        /** @description Создать новый тип события (только владелец). */
        post: operations["EventTypesApi_createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить тип события по ID. */
        get: operations["EventTypesApi_getEventType"];
        /** @description Обновить тип события (только владелец). */
        put: operations["EventTypesApi_updateEventType"];
        post?: never;
        /**
         * @description Удалить тип события (только владелец).
         *     Нельзя удалить тип, если есть активные бронирования.
         */
        delete: operations["EventTypesApi_deleteEventType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить список всех предстоящих встреч (бронирований).
         *     Показывает бронирования всех типов событий в одном списке.
         */
        get: operations["OwnerApi_getUpcomingBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить информацию о владельце календаря.
         *     В системе только один предопределённый владелец.
         */
        get: operations["OwnerApi_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создать бронирование на выбранный слот.
         *     Гость выбирает тип события и свободный слот, указывает свои данные.
         *     Бизнес-правило: нельзя создать две записи на одно и то же время.
         */
        post: operations["GuestPublicApi_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить информацию о бронировании по ID.
         *     Гость может проверить детали своего бронирования.
         */
        get: operations["GuestPublicApi_getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Отменить бронирование.
         *     Гость может отменить своё бронирование.
         */
        post: operations["GuestPublicApi_cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/bookings/{id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Перенести бронирование на другой слот того же типа события.
         *     Освобождает текущий слот и занимает новый в рамках одной транзакции.
         */
        patch: operations["GuestPublicApi_rescheduleBooking"];
        trace?: never;
    };
    "/public/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить список доступных типов бронирования.
         *     Гость видит название, описание и длительность каждого типа.
         */
        get: operations["GuestPublicApi_listPublicEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types/{eventTypeId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить доступные слоты для выбранного типа события.
         *     Гость выбирает тип события и видит свободные слоты в календаре.
         */
        get: operations["GuestPublicApi_getAvailableSlotsForEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить подробную информацию о типе события. */
        get: operations["GuestPublicApi_getPublicEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Получить доступные слоты для бронирования.
         *     Гость использует этот endpoint для выбора свободного слота.
         */
        get: operations["SlotsApi_listAvailableSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить информацию о конкретном слоте. */
        get: operations["SlotsApi_getSlot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Booking - бронирование, создаваемое гостём на выбранный слот.
         *     Содержит информацию о госте и выбранном типе события.
         */
        Booking: {
            /** Format: uuid */
            id: string;
            /** @description Ссылка на тип события */
            eventTypeId: string;
            /** @description Ссылка на забронированный слот */
            slotId: string;
            /** @description Имя гостя */
            guestName: string;
            /**
             * Format: email
             * @description Email гостя
             */
            guestEmail: string;
            /** @description Дополнительные заметки от гостя */
            guestNotes?: string;
            /** @description Статус бронирования */
            status: components["schemas"]["BookingStatus"];
            /**
             * Format: date-time
             * @description Автоматически генерируемая метка времени создания
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Автоматически генерируемая метка времени обновления
             */
            updatedAt: string;
            /** @description Вложенный тип события (включается при получении деталей бронирования) */
            eventType?: components["schemas"]["EventType"];
            /** @description Вложенный слот (включается при получении деталей бронирования) */
            slot?: components["schemas"]["Slot"];
        };
        /**
         * @description Статусы бронирования
         * @enum {string}
         */
        BookingStatus: "confirmed" | "cancelled" | "completed";
        /** @description DTO для отмены бронирования (гость) */
        CancelBookingRequest: {
            /** @description Причина отмены (опционально) */
            reason?: string;
        };
        /** @description DTO для создания бронирования (гость) */
        CreateBookingRequest: {
            /** Format: uuid */
            eventTypeId: string;
            /** Format: uuid */
            slotId: string;
            guestName: string;
            /** Format: email */
            guestEmail: string;
            guestNotes?: string;
        };
        /** @description DTO для создания типа события (владелец) */
        CreateEventTypeRequest: {
            name: string;
            description?: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        ErrorResponse: {
            /** @description Код ошибки */
            code: string;
            /** @description Сообщение об ошибке */
            message: string;
            /** @description Детали ошибки */
            details?: string[];
        };
        /**
         * @description EventType - тип события, создаваемый владельцем календаря.
         *     Каждый тип определяет характеристики встречи (название, описание, длительность).
         */
        EventType: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            /**
             * Format: int32
             * @description Длительность события в минутах
             */
            durationMinutes: number;
            /**
             * Format: date-time
             * @description Автоматически генерируемая метка времени создания
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Автоматически генерируемая метка времени обновления
             */
            updatedAt: string;
        };
        FieldError: {
            field: string;
            message: string;
        };
        NotFoundError: {
            /** @enum {string} */
            code: "NOT_FOUND";
            message: string;
        };
        /**
         * @description Owner - единый предопределённый профиль владельца календаря.
         *     В системе нет регистрации и авторизации, владелец - один заранее заданный профиль.
         */
        Owner: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @description Признак предопределённого системного профиля */
            isPredefined: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description DTO для переноса бронирования на другой слот */
        RescheduleBookingRequest: {
            /**
             * Format: uuid
             * @description UUID нового слота того же типа события
             */
            newSlotId: string;
        };
        /**
         * @description Slot - временной слот в календаре для бронирования.
         *     Слоты генерируются на основе доступности и привязаны ко времени.
         *     Бизнес-правило: на одно и то же время нельзя создать две записи.
         */
        Slot: {
            /** Format: uuid */
            id: string;
            /**
             * Format: date-time
             * @description Время начала слота
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Время окончания слота
             */
            endTime: string;
            /** @description Статус доступности слота */
            isAvailable: boolean;
            /** @description Опциональная ссылка на тип события, если слот привязан к конкретному типу */
            eventTypeId?: string;
            /**
             * Format: date-time
             * @description Автоматически генерируемая метка времени создания
             */
            createdAt: string;
        };
        SlotConflictError: {
            /** @enum {string} */
            code: "SLOT_ALREADY_BOOKED";
            /** @enum {string} */
            message: "Этот слот уже забронирован. На одно и то же время нельзя создать две записи.";
        };
        /** @description DTO для обновления типа события (владелец) */
        UpdateEventTypeRequest: {
            name?: string;
            description?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        ValidationError: {
            /** @enum {string} */
            code: "VALIDATION_ERROR";
            /** @enum {string} */
            message: "Некорректные данные запроса";
            errors: components["schemas"]["FieldError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    EventTypesApi_listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypesApi_createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    EventTypesApi_getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypesApi_updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventTypeRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    EventTypesApi_deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    OwnerApi_getUpcomingBookings: {
        parameters: {
            query?: {
                /** @description Фильтр по статусу */
                status?: components["schemas"]["BookingStatus"];
                /** @description Фильтр по дате начала (включительно) */
                startDate?: string;
                /** @description Фильтр по дате окончания (включительно) */
                endDate?: string;
                /** @description Пагинация - номер страницы */
                page?: number;
                /** @description Пагинация - размер страницы */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    "total-count": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    OwnerApi_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
    GuestPublicApi_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotConflictError"];
                };
            };
        };
    };
    GuestPublicApi_getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    GuestPublicApi_cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GuestPublicApi_rescheduleBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RescheduleBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotConflictError"];
                };
            };
        };
    };
    GuestPublicApi_listPublicEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    GuestPublicApi_getAvailableSlotsForEventType: {
        parameters: {
            query: {
                /** @description Дата начала периода */
                startDate: string;
                /** @description Дата окончания периода */
                endDate: string;
            };
            header?: never;
            path: {
                eventTypeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    GuestPublicApi_getPublicEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    SlotsApi_listAvailableSlots: {
        parameters: {
            query: {
                /** @description Фильтр по типу события */
                eventTypeId?: string;
                /** @description Дата начала периода */
                startDate: string;
                /** @description Дата окончания периода */
                endDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    SlotsApi_getSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
}
export enum ApiPaths {
    EventTypesApi_listEventTypes = "/event-types",
    EventTypesApi_createEventType = "/event-types",
    EventTypesApi_getEventType = "/event-types/{id}",
    EventTypesApi_updateEventType = "/event-types/{id}",
    EventTypesApi_deleteEventType = "/event-types/{id}",
    OwnerApi_getUpcomingBookings = "/owner/bookings",
    OwnerApi_getProfile = "/owner/profile",
    GuestPublicApi_createBooking = "/public/bookings",
    GuestPublicApi_getBooking = "/public/bookings/{id}",
    GuestPublicApi_cancelBooking = "/public/bookings/{id}/cancel",
    GuestPublicApi_rescheduleBooking = "/public/bookings/{id}/reschedule",
    GuestPublicApi_listPublicEventTypes = "/public/event-types",
    GuestPublicApi_getAvailableSlotsForEventType = "/public/event-types/{eventTypeId}/slots",
    GuestPublicApi_getPublicEventType = "/public/event-types/{id}",
    SlotsApi_listAvailableSlots = "/slots",
    SlotsApi_getSlot = "/slots/{id}"
}
